### ISSUE TITLE
Unable to DM joining users

### ISSUE THREAD

**Issue by robbai** [FelixRandle/Sheffield-Discord-Bot#26]
Looks like [this method](https://github.com/FelixRandle/Sheffield-Discord-Bot/blob/7faba1debcbfa29855fa48f7cec5fbd0fd83b194/main.py#L59-L87) wasn't triggered when I (r0bbi3#0269) joined.
This is likely caused by [this setting](https://user-images.githubusercontent.com/42142350/92980905-a68d4c00-f48f-11ea-9dc7-7829d29adc93.png) being disabled.
This has left me with 0 roles in the server, and therefore [no access to the rest of the server](https://user-images.githubusercontent.com/42142350/92980949-d5a3bd80-f48f-11ea-91f4-33a2e268125c.png).
Perhaps it's better to place the lines of code that direct message the user in a try-except block, so the method doesn't throw an error before giving the user their "registering" role.

**Comment by FelixRandle** [comment]
Cheers for the investigation, in the meantime, have you got roles to actually view the server

**Comment by robbai** [comment]
Thanks.
