### ISSUE TITLE
compfessions: allow mentioning previous compfessions in compfessions

### ISSUE THREAD

**Issue by WilliamWFLee** [FelixRandle/Sheffield-Discord-Bot#81]
Similar to existing mention system for mentioning compfessions in conversation, but for within compfessions themselves

**Comment by SamTheDude** [comment]
What would be the expected behavior of mentioning a compfession from within itself?

**Comment by WilliamWFLee** [comment]
@SamTheDude Thanks for pointing this out. The expected behaviour should be that the mention is ignored, however this has not been tested. I'll get back to you when tests have been carried out.

**Comment by WilliamWFLee** [comment]
I've conducted a test, and no errors are directly caused by the fact that a compfession mentions itself. However, it has revealed a bug in #83 for this issue related to fetching the message for the mentioned compfession when no such compfession exists. Gonna patch this with a commit now.
